# -*- coding: utf-8 -*-
"""batch_inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HsNuIb9oREZqXSLH9R2x6yDBlC7tvm-
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import drive
drive.mount("/Test_35_points")

!pip install ultralytics

import sys
import cv2
import numpy as np
import os
from ultralytics import YOLO
# model = YOLO('https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-pose.pt')
model=YOLO('/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/best.pt')

Images_folderpath = "/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/val_dataset_coco35/images/test"

images = []
for img in os.listdir(Images_folderpath):
    images.append(cv2.imread(os.path.join(Images_folderpath, img)))

# Create image list
batch_size = 20
imgs = []
for i in range(batch_size):
    imgs.append(images[i])
print(len(imgs))

#%% Pass in the entire imgs list
# inference_times = np.empty(len(imgs))

dt_total_list = []
print("batch size : ",len(imgs))
predictions = model.predict(source=imgs, save=False, save_conf=True, max_det=1, show=False, stream=False, device=0)

for prediction in predictions:
    dt_dict = prediction.speed
    dt = []
    for key, value in dt_dict.items():
        dt.append(value)
    dt_total = sum(dt)
    dt_total_list.append(dt_total)

inference_times = np.array(dt_total_list)

print(f"Average Inference Speed: {np.mean(inference_times):.2f}")





