# -*- coding: utf-8 -*-
"""Train YOLO_35Keypoints.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11EUnB44vKP0Vt5H10Mj9zEIf4tY91zZf
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import drive
drive.mount("/Test_35_points")


!pip install ultralytics

# from ultralytics import YOLO
# # model = YOLO('https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8x-pose.pt')



# model.train(data='/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/data.yaml', epochs=20, imgsz=1280)

# !pip show torch

from ultralytics import YOLO
model = YOLO('/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/last.pt')  # load a custom model

# Predict with the model
# results = model.predict('/Test_35_points/MyDrive/yolov8/COCO_5000/Yolov8_Dataset/images/test/000000000785.jpg')  # predict on an image


# Run inference on 'bus.jpg' with arguments
img=cv2.imread('/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/val_dataset_coco35/images/test/000000005193.jpg')
r=model.predict(img, save=True, imgsz=1280, conf=0.30,boxes=False,show_labels=False)

a_f=r[0].plot()
# r=model(results)
cv2_imshow(a_f)


"""# Predict images without BBoxes"""

!yolo predict model='/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/last.pt' source='/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/val_dataset_coco35/images/test/000000005193.jpg' show=False boxes=False


a_f=r[0].plot()
# r=model(results)
cv2_imshow(a_f)

results = model('/Test_35_points/MyDrive/YOLOv8_Train_35Keypoints/val_dataset_coco35/images/test/000000280930.jpg')[0]

for result in results:
    for keypoint_indx, keypoint in enumerate(result.keypoints.tolist()):
        cv2.putText(img, str(keypoint_indx), (int(keypoint[0]), int(keypoint[1])),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

cv2_imshow('img', img)
cv2.waitKey(0)



